// Shared by tests/test_protobuf.cpp, fuzz/fuzz_protobuf.cpp and tests/protobuf_dump.cpp: random
// values of any protobuf message model, generated BY REFLECTION (every field; zeros and empties
// often, so default-skipping is exercised; optional ones present or not), and deep field-by-field
// equality.
#ifndef NANOM_TESTS_PROTOBUF_GEN_HPP_INCLUDED
#define NANOM_TESTS_PROTOBUF_GEN_HPP_INCLUDED

#include <nanom/protobuf.hpp>

#include <algorithm>
#include <cstring>
#include <deque>
#include <limits>
#include <memory>
#include <random>
#include <string>

namespace nanom_test::pb {
namespace nm = nanom;

/// Owns everything generated views point at.
struct arena {
  std::deque<std::string> strings;
  std::deque<std::shared_ptr<void>> objects;  ///< messages pb_lazy<M>::of() points at
};

template <class T> T gen(std::mt19937_64& rng, arena& a, int depth);

template <class I>
I gen_int(std::mt19937_64& rng) {
  const auto r = rng();
  if (r % 4 == 0) return I(0);
  if (r % 3 == 0) return I(std::int64_t(r % 200) - (std::is_signed_v<I> ? 100 : 0));
  if (r % 7 == 0) return (r & 8) ? std::numeric_limits<I>::max() : std::numeric_limits<I>::min();
  return I(r >> (r % 64));  // every width of varint
}

inline std::string_view gen_string(std::mt19937_64& rng, arena& a) {
  std::string s(rng() % 3 == 0 ? 0 : rng() % (rng() % 9 == 0 ? 300 : 12), '\0');
  for (auto& c : s) c = char(rng());
  a.strings.push_back(std::move(s));
  return a.strings.back();
}

/// Valid wire records for fields message M does not declare (any wire type, ids past 32767
/// included), as a pb_unknown member holds them.
template <class M>
nm::unknown_fields gen_unknown(std::mt19937_64& rng) {
  nm::unknown_fields u;
  const auto put = [&](std::uint64_t v) {
    std::byte b[10];
    const auto n = nm::uleb128_encode(v, b);
    u.bytes.insert(u.bytes.end(), b, b + n);
  };
  const auto& ids = nm::detail::message_info<M>::ids;
  for (int k = int(rng() % 4); k > 0; --k) {
    std::uint64_t id;
    do {
      id = rng() % 3 ? 1 + rng() % 200 : 1 + rng() % 536870911;
    } while (std::find(ids.begin(), ids.end(), id) != ids.end());
    const std::uint8_t wts[] = {0, 1, 2, 5};
    const std::uint8_t wt = wts[rng() % 4];
    put((id << 3) | wt);
    if (wt == 0) put(rng() >> (rng() % 64));
    else if (wt == 1 || wt == 5)
      for (int i = 0; i < (wt == 1 ? 8 : 4); ++i) u.bytes.push_back(std::byte(rng()));
    else {
      const std::size_t n = rng() % 20;
      put(n);
      for (std::size_t i = 0; i < n; ++i) u.bytes.push_back(std::byte(rng()));
    }
  }
  return u;
}

template <class T>
T gen(std::mt19937_64& rng, arena& a, int depth) {
  if constexpr (std::is_same_v<T, std::string_view>) {
    return gen_string(rng, a);
  } else if constexpr (std::is_same_v<T, std::string>) {
    return std::string(gen_string(rng, a));
  } else if constexpr (std::is_same_v<T, nm::empty_struct>) {
    return {};
  } else if constexpr (nm::detail::pb::is_lazy_pb<T>::value) {  // a message held by the arena
    auto m = std::make_shared<typename T::value_type>(gen<typename T::value_type>(rng, a, depth));
    a.objects.push_back(m);
    return T::of(*m);
  } else if constexpr (std::is_same_v<T, nm::bytes>) {
    const auto s = gen_string(rng, a);
    return nm::bytes(reinterpret_cast<const std::byte*>(s.data()), s.size());
  } else if constexpr (nm::detail::pb::is_sint<T>::value || nm::detail::pb::is_fixed<T>::value) {
    return T(gen_int<decltype(T{}.v)>(rng));
  } else if constexpr (std::is_same_v<T, bool>) {
    return rng() & 1;
  } else if constexpr (std::is_enum_v<T>) {  // open enums: any int32
    return T(gen_int<std::int32_t>(rng));
  } else if constexpr (std::is_floating_point_v<T>) {
    using U = std::conditional_t<sizeof(T) == 4, std::uint32_t, std::uint64_t>;
    const auto r = rng();
    if (r % 4 == 0) return T(0);
    if (r % 4 == 1) return -T(0);  // -0.0 is not the default: it is written
    return std::bit_cast<T>(U(r));  // any bit pattern, NaNs included (compared bitwise)
  } else if constexpr (std::is_integral_v<T>) {
    return gen_int<T>(rng);
  } else if constexpr (nm::detail::is_vector_t<T>::value) {
    using E = typename T::value_type;
    const std::size_t n = depth > 4 || rng() % 3 == 0 ? 0 : rng() % (rng() % 6 == 0 ? 60 : 4);
    T v;
    for (std::size_t i = 0; i < n; ++i) v.push_back(gen<E>(rng, a, depth + 1));
    return v;
  } else if constexpr (nm::Message<T>) {
    T m{};
    nm::detail::for_each_field<T>([&](auto f) {
      using F = nm::detail::member_t<decltype(f)::mem_ptr>;
      using V = typename F::value_type;
      auto& slot = (m.*(decltype(f)::mem_ptr)).v;
      if constexpr (std::is_same_v<V, nm::unknown_fields>) {
        slot = gen_unknown<T>(rng);
      } else if constexpr (nm::detail::is_box_t<V>::value) {
        if (depth < 5 && rng() % 2) slot = gen<typename V::value_type>(rng, a, depth + 1);
      } else if constexpr (nm::detail::pb::is_lazy_pb<V>::value) {
        if (depth < 5 && rng() % 2) slot = gen<V>(rng, a, depth + 1);
      } else if constexpr (nm::detail::is_optional_t<V>::value) {
        if (depth < 6 && rng() % 3) slot = gen<typename V::value_type>(rng, a, depth + 1);
      } else {
        slot = gen<V>(rng, a, depth + 1);
      }
    });
    return m;
  } else {
    static_assert(nm::detail::tc::always_false<T>, "protobuf_gen: unsupported member type");
  }
}

template <class T>
bool same(const T& x, const T& y) {
  if constexpr (std::is_floating_point_v<T>) {
    using U = std::conditional_t<sizeof(T) == 4, std::uint32_t, std::uint64_t>;
    return std::bit_cast<U>(x) == std::bit_cast<U>(y);
  } else if constexpr (std::is_same_v<T, nm::bytes>) {
    return x.size() == y.size() && (x.size() == 0 || std::memcmp(x.data(), y.data(), x.size()) == 0);
  } else if constexpr (nm::detail::is_optional_t<T>::value || nm::detail::is_box_t<T>::value) {
    return x.has_value() == y.has_value() && (!x || same(*x, *y));
  } else if constexpr (nm::detail::pb::is_lazy_pb<T>::value) {
    if (x.has_value() != y.has_value()) return false;
    if (!x) return true;
    const auto rx = x.region(), ry = y.region();  // both read from the wire: the same bytes
    if (!x.source() && !y.source())
      return rx.size() == ry.size() && (rx.empty() || std::memcmp(rx.data(), ry.data(), rx.size()) == 0);
    auto a = x.decode(), b = y.decode();  // otherwise what they decode to
    return a && b && same(*a, *b);
  } else if constexpr (nm::detail::is_vector_t<T>::value) {
    if (x.size() != y.size()) return false;
    for (std::size_t i = 0; i < x.size(); ++i)
      if (!same<typename T::value_type>(x[i], y[i])) return false;
    return true;
  } else if constexpr (nm::Message<T>) {
    bool ok = true;
    nm::detail::for_each_field<T>([&](auto f) {
      ok = ok && same((x.*(decltype(f)::mem_ptr)).v, (y.*(decltype(f)::mem_ptr)).v);
    });
    return ok;
  } else {
    return x == y;
  }
}

}  // namespace nanom_test::pb

#endif  // NANOM_TESTS_PROTOBUF_GEN_HPP_INCLUDED
