// protobuf_oracle — the C++ side of tests/protobuf_differential.py (Google's protobuf runtime as
// the oracle for nanom/protobuf.hpp + nanom/protobuf_encode.hpp over the Lance model).
//
//   protobuf_oracle gen N SEED   print N random messages (generated by reflection) as
//                                "<Type> <hex>" lines, encoded by nanom
//   protobuf_oracle recode       for each "<Type> <hex>" line on stdin: decode with nanom and print
//                                "<Type> <hex of the re-encoding>" (or "<Type> ERROR <why>")
#include <nanom/formats/lance_protobuf.hpp>
#include <nanom/protobuf_encode.hpp>

#include "protobuf_gen.hpp"

#include <cstdio>
#include <cstdlib>
#include <iostream>
#include <random>
#include <string>
#include <vector>

namespace nm = nanom;
namespace lance = nanom_formats::lance;

static std::string hex(const std::vector<std::byte>& b) {
  static const char* d = "0123456789abcdef";
  std::string s;
  for (auto x : b) {
    s += d[std::uint8_t(x) >> 4];
    s += d[std::uint8_t(x) & 15];
  }
  return s;
}
static std::vector<std::byte> unhex(const std::string& s) {
  std::vector<std::byte> b;
  for (std::size_t i = 0; i + 1 < s.size(); i += 2) b.push_back(std::byte(std::stoi(s.substr(i, 2), nullptr, 16)));
  return b;
}

/// A reader that declares a few of Manifest's fields and keeps the rest (pb_unknown): re-encoding
/// it must lose nothing, at the top level or inside fragments.
struct FragmentLite {
  nm::pb_unknown                                        unknown;
  nm::field<1, std::uint64_t, nm::presence::defaulted>  id;
};
struct ManifestLite {
  nm::pb_unknown                                                    unknown;
  nm::field<2, std::vector<FragmentLite>, nm::presence::defaulted>  fragments;
  nm::field<3, std::uint64_t, nm::presence::defaulted>              version;
};
NANOM_DESCRIBE(FragmentLite, unknown, id);
NANOM_DESCRIBE(ManifestLite, unknown, fragments, version);

template <class F>
static bool with_type(const std::string& name, F&& f) {
  if (name == "ManifestLite") return f(ManifestLite{}), true;
  if (name == "IndexMetadata") return f(lance::IndexMetadata{}), true;
  if (name == "IndexSection") return f(lance::IndexSection{}), true;
  if (name == "Manifest") return f(lance::Manifest{}), true;
  if (name == "FileDescriptor") return f(lance::FileDescriptor{}), true;
  if (name == "ColumnMetadata") return f(lance::ColumnMetadata{}), true;
  if (name == "Metadata") return f(lance::Metadata{}), true;
  if (name == "DataFragment") return f(lance::DataFragment{}), true;
  return false;
}

int main(int argc, char** argv) {
  if (argc >= 2 && std::string(argv[1]) == "gen") {
    const int n = argc > 2 ? std::atoi(argv[2]) : 100;
    std::mt19937_64 rng(argc > 3 ? std::strtoull(argv[3], nullptr, 10) : 1);
    const char* names[] = {"Manifest", "FileDescriptor", "ColumnMetadata", "Metadata", "DataFragment",
                           "IndexMetadata", "IndexSection"};
    for (int i = 0; i < n; ++i) {
      const std::string name = names[i % 7];
      with_type(name, [&]<class M>(M) {
        nanom_test::pb::arena a;
        const M m = nanom_test::pb::gen<M>(rng, a, 0);
        std::vector<std::byte> out;
        if (!nm::protobuf_encode(m, out)) std::exit(2);
        std::printf("%s %s\n", name.c_str(), out.empty() ? "-" : hex(out).c_str());
      });
    }
    return 0;
  }
  if (argc >= 2 && std::string(argv[1]) == "recode") {
    std::string name, h;
    while (std::cin >> name >> h) {
      if (h == "-") h.clear();
      const auto in = unhex(h);
      const bool known = with_type(name, [&]<class M>(M) {
        auto r = nm::protobuf<M>()(nm::from(std::span<const std::byte>(in)));
        if (!r) {
          std::printf("%s ERROR %s\n", name.c_str(), r.error().expected);
          return;
        }
        std::vector<std::byte> out;
        if (auto e = nm::protobuf_encode(r->value, out); !e) {
          std::printf("%s ERROR %s\n", name.c_str(), e.error().what);
          return;
        }
        std::printf("%s %s\n", name.c_str(), out.empty() ? "-" : hex(out).c_str());
      });
      if (!known) return 2;
    }
    return 0;
  }
  std::fprintf(stderr, "usage: protobuf_oracle gen N SEED | recode\n");
  return 2;
}
