// Shared by tests/test_tagged_encode.cpp and fuzz/fuzz_thrift.cpp: random values of any tagged
// message, generated BY REFLECTION (every field, optional ones present or not, random strings,
// lists built with list<E>::of), and deep field-by-field equality.
#ifndef NANOM_TESTS_TAGGED_GEN_HPP_INCLUDED
#define NANOM_TESTS_TAGGED_GEN_HPP_INCLUDED

#include <nanom/tagged.hpp>

#include <cstring>
#include <deque>
#include <limits>
#include <memory>
#include <random>
#include <string>

namespace nanom_test {
namespace nm = nanom;

/// Owns everything the generated views point at (strings, list elements).
struct arena {
  std::deque<std::string> strings;
  std::deque<std::shared_ptr<void>> lists;
};

template <class T> T gen(std::mt19937_64& rng, arena& a, int depth);

template <class T>
T gen_scalar(std::mt19937_64& rng) {
  if constexpr (std::is_same_v<T, bool>) {
    return rng() & 1;
  } else if constexpr (std::is_enum_v<T>) {
    // open enums: any int32 round-trips, known or not
    const auto r = rng();
    return T(std::int32_t(r % 4 == 0 ? std::int64_t(r >> 32) - (std::int64_t(1) << 31) : std::int64_t(r % 10)));
  } else if constexpr (std::is_same_v<T, double>) {
    return std::bit_cast<double>(rng());  // any bit pattern, NaNs included (compared bitwise)
  } else {
    // mix small values (one-byte varints) with full-width extremes
    const auto r = rng();
    if (r % 3 == 0) return T(std::int64_t(r % 200) - 100);
    if (r % 7 == 0) return (r & 8) ? std::numeric_limits<T>::max() : std::numeric_limits<T>::min();
    return T(r);
  }
}

inline std::string_view gen_string(std::mt19937_64& rng, arena& a) {
  std::string s(rng() % (rng() % 9 == 0 ? 300 : 12), '\0');
  for (auto& c : s) c = char(rng());
  a.strings.push_back(std::move(s));
  return a.strings.back();
}

template <class T>
T gen(std::mt19937_64& rng, arena& a, int depth) {
  if constexpr (std::is_same_v<T, std::string_view>) {
    return gen_string(rng, a);
  } else if constexpr (std::is_same_v<T, nm::bytes>) {
    const auto s = gen_string(rng, a);
    return nm::bytes(reinterpret_cast<const std::byte*>(s.data()), s.size());
  } else if constexpr (std::is_same_v<T, nm::empty_struct>) {
    return {};
  } else if constexpr (nm::detail::is_list_t<T>::value) {
    using E = typename T::value_type;
    // a plain array, not std::vector (vector<bool> has no contiguous span)
    const std::size_t n = depth > 3 ? 0 : rng() % (rng() % 5 == 0 ? 40 : 4);
    std::shared_ptr<E[]> v(new E[n ? n : 1]());
    for (std::size_t i = 0; i < n; ++i) v[i] = gen<E>(rng, a, depth + 1);
    a.lists.push_back(v);
    return T::of(std::span<const E>(v.get(), n));
  } else if constexpr (nm::Message<T>) {
    T m{};
    nm::detail::for_each_field<T>([&](auto f) {
      using F = nm::detail::member_t<decltype(f)::mem_ptr>;
      using V = typename F::value_type;
      auto& slot = (m.*(decltype(f)::mem_ptr)).v;
      if constexpr (nm::detail::is_optional_t<V>::value) {
        if (rng() % 3) slot = gen<typename V::value_type>(rng, a, depth + 1);
      } else {
        slot = gen<V>(rng, a, depth + 1);
      }
    });
    return m;
  } else {
    return gen_scalar<T>(rng);
  }
}

template <class T> bool same(const T& x, const T& y);

template <class T>
bool same(const T& x, const T& y) {
  if constexpr (std::is_same_v<T, double>) {
    return std::bit_cast<std::uint64_t>(x) == std::bit_cast<std::uint64_t>(y);
  } else if constexpr (std::is_same_v<T, nm::bytes>) {
    return x.size() == y.size() && (x.size() == 0 || std::memcmp(x.data(), y.data(), x.size()) == 0);
  } else if constexpr (std::is_same_v<T, nm::empty_struct>) {
    return true;
  } else if constexpr (nm::detail::is_optional_t<T>::value) {
    return x.has_value() == y.has_value() && (!x || same(*x, *y));
  } else if constexpr (nm::detail::is_list_t<T>::value) {
    auto a = x.to_vector(), b = y.to_vector();
    if (!a || !b || a->size() != b->size()) return false;
    for (std::size_t i = 0; i < a->size(); ++i)
      if (!same((*a)[i], (*b)[i])) return false;
    return true;
  } else if constexpr (nm::Message<T>) {
    bool ok = true;
    nm::detail::for_each_field<T>([&](auto f) {
      ok = ok && same((x.*(decltype(f)::mem_ptr)).v, (y.*(decltype(f)::mem_ptr)).v);
    });
    return ok;
  } else {
    return x == y;
  }
}

}  // namespace nanom_test

#endif  // NANOM_TESTS_TAGGED_GEN_HPP_INCLUDED
