// Tests for nanom/protobuf.hpp (decode) and nanom/protobuf_encode.hpp (encode).
//
//   * golden bytes from the protobuf encoding spec (varints, negative int32, zigzag, fixed, packed,
//     strings, nested messages) in both directions;
//   * property tests over a message using every member type, a recursive message and the whole
//     Lance model (nanom/formats/lance_protobuf.hpp). Random values GENERATED BY REFLECTION, then:
//       decode(encode(x)) == x;  encode(decode(encode(x))) is byte-identical;
//       protobuf_size(x) == bytes written;  every too-small span_sink fails cleanly;
//   * the reader's protobuf rules: unpacked and packed repeated both accepted (and merged), unknown
//     fields of every wire type skipped, a known field with another wire type skipped, repeated
//     message fields merged, the last scalar wins;
//   * hostile input: truncation at every byte, over-long varints, out-of-range integers, groups,
//     field number 0, lengths past the end, nesting bombs, missing required fields;
//   * encoder errors: failing sinks, nesting beyond the decoder's limit, with the location named.
#include <nanom/formats/lance_protobuf.hpp>
#include <nanom/protobuf_encode.hpp>

#include "protobuf_gen.hpp"

#include <cstdio>
#include <initializer_list>
#include <random>
#include <string>
#include <vector>

namespace nm = nanom;
namespace lance = nanom_formats::lance;
using nanom_test::pb::arena;
using nanom_test::pb::gen;
using nanom_test::pb::same;

static int failures = 0;
#define CHECK(cond)                                                        \
  do {                                                                     \
    if (!(cond)) {                                                         \
      std::printf("FAIL %s:%d: %s\n", __FILE__, __LINE__, #cond);          \
      ++failures;                                                          \
    }                                                                      \
  } while (0)

template <std::uint16_t Id, class T>
using pf = nm::field<Id, T, nm::presence::defaulted>;

enum class Color : std::int32_t { RED = 0, GREEN = 1 };

struct Leaf {
  pf<1, std::int32_t>     a;
  pf<2, std::string_view> s;
};
/// Every member type the codec supports.
struct All {
  pf<1, std::int32_t>                       i32;
  pf<2, std::int64_t>                       i64;
  pf<3, std::uint32_t>                      u32;
  pf<4, std::uint64_t>                      u64;
  pf<5, nm::pb_sint<std::int32_t>>          s32;
  pf<6, nm::pb_sint<std::int64_t>>          s64;
  pf<7, nm::pb_fixed<std::uint32_t>>        f32;
  pf<8, nm::pb_fixed<std::int64_t>>         sf64;
  pf<9, float>                              fl;
  pf<10, double>                            db;
  pf<11, bool>                              b;
  pf<12, Color>                             color;
  pf<13, std::string_view>                  sv;
  pf<14, std::string>                       str;
  pf<15, nm::bytes>                         by;
  pf<16, Leaf>                              leaf;
  nm::field<17, std::optional<Leaf>>        maybe_leaf;
  nm::field<18, std::optional<std::int32_t>> maybe_i32;
  pf<19, std::vector<std::int32_t>>         r_i32;
  pf<20, std::vector<nm::pb_sint<std::int64_t>>> r_s64;
  pf<21, std::vector<nm::pb_fixed<std::uint32_t>>> r_f32;
  pf<22, std::vector<double>>               r_db;
  pf<23, std::vector<bool>>                 r_b;
  pf<24, std::vector<Color>>                r_color;
  pf<25, std::vector<std::string_view>>     r_sv;
  pf<26, std::vector<nm::bytes>>            r_by;
  pf<27, std::vector<Leaf>>                 r_leaf;
  nm::field<28, std::int64_t>               req;  // presence::required
  pf<536, std::uint64_t>                    big_id;  // a two-byte key
};
/// A recursive message (a tree).
struct Node {
  pf<1, std::int32_t>      v;
  pf<2, std::vector<Node>> kids;
};
NANOM_DESCRIBE(Leaf, a, s);
NANOM_DESCRIBE(All, i32, i64, u32, u64, s32, s64, f32, sf64, fl, db, b, color, sv, str, by, leaf, maybe_leaf,
               maybe_i32, r_i32, r_s64, r_f32, r_db, r_b, r_color, r_sv, r_by, r_leaf, req, big_id);
NANOM_DESCRIBE(Node, v, kids);

static std::vector<std::byte> B(std::initializer_list<int> v) {
  std::vector<std::byte> out;
  for (int x : v) out.push_back(std::byte(x));
  return out;
}
static nm::input in_of(const std::vector<std::byte>& b) { return nm::from(std::span<const std::byte>(b)); }
template <class M>
static std::vector<std::byte> enc(const M& m) {
  std::vector<std::byte> out;
  auto r = nm::protobuf_encode(m, out);
  CHECK(r && *r == out.size());
  return out;
}

// ------------------------------------------------------------------ properties
template <class M>
void roundtrip_property(const char* name, int rounds, std::uint64_t seed) {
  std::mt19937_64 rng(seed);
  int bad = 0;
  for (int t = 0; t < rounds; ++t) {
    arena a;
    const M x = gen<M>(rng, a, 0);

    std::vector<std::byte> wire;
    auto n = nm::protobuf_encode(x, wire);
    if (!n || *n != wire.size()) { ++bad; continue; }
    auto size = nm::protobuf_size(x);
    if (!size || *size != wire.size()) { ++bad; continue; }

    auto back = nm::protobuf<M>()(in_of(wire));
    if (!back || !back->rest.empty() || !same(x, back->value)) { ++bad; continue; }

    std::vector<std::byte> again;  // canonical: re-encoding the decoded message is byte-identical
    if (!nm::protobuf_encode(back->value, again) || again != wire) { ++bad; continue; }

    {
      std::vector<std::byte> exact(wire.size());
      nm::span_sink s{exact};
      if (!nm::protobuf_encode(x, s) || exact != wire) { ++bad; continue; }
    }
    const std::size_t step = wire.size() > 64 ? wire.size() / 16 : 1;
    for (std::size_t cap = 0; cap < wire.size(); cap += step) {
      std::vector<std::byte> small(cap);  // exact capacity: ASan catches any write past it
      nm::span_sink s{small};
      if (nm::protobuf_encode(x, s) || s.used > cap) { ++bad; break; }
    }
    // every strict prefix of a message is either a valid (shorter) message or an error, never a
    // crash or an over-read (ASan); a cut inside a varint or a length always fails
    for (std::size_t cut = 0; cut < wire.size(); cut += step) {
      std::vector<std::byte> prefix(wire.begin(), wire.begin() + std::ptrdiff_t(cut));
      (void)nm::protobuf<M>()(in_of(prefix));
    }
  }
  if (bad) std::printf("%s: %d of %d rounds failed\n", name, bad, rounds);
  CHECK(bad == 0);
}

// ------------------------------------------------------------------ golden bytes (the spec's)
struct Golden {
  pf<1, std::int32_t>                  a;
  pf<2, std::string_view>              b;
  nm::field<3, std::optional<Leaf>>    c;
  pf<4, std::vector<std::int32_t>>     d;
};
struct Signed {
  pf<1, nm::pb_sint<std::int32_t>>  s32;
  pf<2, nm::pb_sint<std::int64_t>>  s64;
  pf<3, nm::pb_fixed<std::uint32_t>> f32;
  pf<4, double>                     db;
  pf<5, bool>                       b;
};
struct Opt {
  nm::field<1, std::optional<std::int32_t>> v;
};
struct Wrap {
  pf<1, Leaf> l;
};
NANOM_DESCRIBE(Golden, a, b, c, d);
NANOM_DESCRIBE(Wrap, l);
NANOM_DESCRIBE(Signed, s32, s64, f32, db, b);
NANOM_DESCRIBE(Opt, v);

static void test_golden() {
  Golden g;
  g.a = 150;
  CHECK(enc(g) == B({0x08, 0x96, 0x01}));
  g = {};
  g.b = std::string_view("testing");
  CHECK(enc(g) == B({0x12, 0x07, 't', 'e', 's', 't', 'i', 'n', 'g'}));
  g = {};
  g.c = Leaf{};
  g.c->value().a = 150;
  CHECK(enc(g) == B({0x1a, 0x03, 0x08, 0x96, 0x01}));
  CHECK(enc(Wrap{}) == B({0x0a, 0x00}));  // a message member is always written, even when empty
  g = {};
  g.d.v = {3, 270, 86942};
  const auto packed = B({0x22, 0x06, 0x03, 0x8e, 0x02, 0x9e, 0xa7, 0x05});
  CHECK(enc(g) == packed);
  g = {};
  g.a = -1;  // negative int32: sign-extended to 64 bits, 10 bytes
  CHECK(enc(g) == B({0x08, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0x01}));
  auto back = nm::protobuf<Golden>()(in_of(enc(g)));
  CHECK(back && *back->value.a == -1);

  Signed s;
  CHECK(enc(s).empty());  // every default is left out
  s.s32 = nm::pb_sint<std::int32_t>(-1);
  s.s64 = nm::pb_sint<std::int64_t>(-2);
  s.f32 = nm::pb_fixed<std::uint32_t>(1);
  s.db = 1.0;
  s.b = true;
  CHECK(enc(s) == B({0x08, 0x01, 0x10, 0x03, 0x1d, 0x01, 0x00, 0x00, 0x00, 0x21, 0, 0, 0, 0, 0, 0, 0xf0, 0x3f,
                     0x28, 0x01}));
  s = {};
  s.db = -0.0;  // -0.0 is not the default
  CHECK(enc(s).size() == 9);

  Opt o;
  CHECK(enc(o).empty());
  o.v = 0;  // explicit presence: a present zero is written
  CHECK(enc(o) == B({0x08, 0x00}));
  auto ob = nm::protobuf<Opt>()(in_of(enc(o)));
  CHECK(ob && ob->value.v->has_value() && **ob->value.v == 0);
  auto oe = nm::protobuf<Opt>()(in_of({}));
  CHECK(oe && !oe->value.v->has_value());
}

// ------------------------------------------------------------------ reader rules
static void test_reader_rules() {
  // unpacked repeated (proto2 style) is accepted, and mixes with packed runs in order
  auto r = nm::protobuf<Golden>()(in_of(B({0x20, 0x01, 0x22, 0x02, 0x02, 0x03, 0x20, 0x04})));
  CHECK(r && r->value.d->size() == 4 && (*r->value.d)[0] == 1 && (*r->value.d)[3] == 4);

  // unknown fields of every wire type are skipped; so is a known field with the wrong wire type
  auto u = nm::protobuf<Golden>()(in_of(B({
      0x48, 0x05,                                      // 9: varint
      0x51, 1, 2, 3, 4, 5, 6, 7, 8,                    // 10: fixed64
      0x5a, 0x02, 0xaa, 0xbb,                          // 11: len
      0x65, 1, 2, 3, 4,                                // 12: fixed32
      0x0d, 1, 2, 3, 4,                                // 1 (int32) as fixed32: skipped
      0x80, 0x80, 0x80, 0x80, 0x01, 0x00,              // field 2^25 (> 32767): skipped
      0x08, 0x07})));                                  // 1: 7
  CHECK(u && *u->value.a == 7 && u->rest.empty());

  // the last scalar wins; a repeated message field merges
  const auto mb = B({0x08, 0x01, 0x08, 0x02, 0x1a, 0x02, 0x08, 0x05, 0x1a, 0x03, 0x12, 0x01, 'x'});
  auto m = nm::protobuf<Golden>()(in_of(mb));  // (views point into mb: keep it alive)
  CHECK(m && *m->value.a == 2 && m->value.c->has_value() && *m->value.c->value().a == 5 &&
        *m->value.c->value().s == "x");
}

// ------------------------------------------------------------------ hostile input
static void test_hostile() {
  const auto bad = [](std::vector<std::byte> b) { return !nm::protobuf<Golden>()(in_of(b)); };
  CHECK(bad(B({0x08})));                                  // value missing
  CHECK(bad(B({0x08, 0x80})));                            // truncated varint
  CHECK(bad(B({0x08, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x01})));  // 11 bytes
  CHECK(bad(B({0x08, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0x02})));  // > 64 bits
  CHECK(bad(B({0x08, 0x80, 0x80, 0x80, 0x80, 0x10})));    // 2^32 does not fit int32
  CHECK(bad(B({0x12, 0x05, 'a'})));                       // length past the end
  CHECK(bad(B({0x12, 0xff, 0xff, 0xff, 0xff, 0x0f})));    // huge length
  CHECK(bad(B({0x0b, 0x0c})));                            // a group (wire type 3)
  CHECK(bad(B({0x0f})));                                  // wire type 7
  CHECK(bad(B({0x00, 0x00})));                            // field number 0
  CHECK(bad(B({0x22, 0x02, 0x01})));                      // packed run past the end
  CHECK(bad(B({0x22, 0x01, 0x80})));                      // packed run cut inside a varint
  CHECK(bad(B({0x1a, 0x01, 0x80})));                      // nested message cut inside a varint
  CHECK(!nm::protobuf<Signed>()(in_of(B({0x28, 0x02}))));  // bool must be 0 or 1
  // the 10th varint byte carries bit 63 only: 0x01 is the largest uint64, 0x02 overflows
  const auto u64max = B({0x08, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0x01});
  auto um = nm::protobuf<lance::Metadata>()(in_of(u64max));
  CHECK(um && *um->value.manifest_position == UINT64_MAX);
  CHECK(!nm::protobuf<lance::Metadata>()(in_of(B({0x08, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0x02}))));
  CHECK(!nm::protobuf<Signed>()(in_of(B({0x1d, 0x01, 0x00}))));  // fixed32 cut short

  // a missing required field is an error naming the message
  auto req = nm::protobuf<All>()(in_of({}));
  CHECK(!req);
  All all;
  all.req = 0;  // required: written even when zero
  auto ab = enc(all);
  auto ar = nm::protobuf<All>()(in_of(ab));
  CHECK(ar && *ar->value.req == 0);

  // nesting bomb: the decoder stops at max_tagged_depth instead of recursing without bound
  std::vector<std::byte> bomb;
  for (int i = 0; i < 2000; ++i) {
    std::vector<std::byte> next = B({0x12});
    std::byte len[10];
    const auto n = nm::uleb128_encode(std::uint64_t(bomb.size()), len);
    next.insert(next.end(), len, len + n);
    next.insert(next.end(), bomb.begin(), bomb.end());
    bomb = std::move(next);
    if (bomb.size() > 20000) break;
  }
  CHECK(!nm::protobuf<Node>()(in_of(bomb)));
}

// ------------------------------------------------------------------ encoder errors
struct failing_sink {
  std::size_t budget;
  bool put(const std::byte*, std::size_t n) {
    if (n > budget) return false;
    budget -= n;
    return true;
  }
};

static void test_encode_errors() {
  // nesting as deep as the decoder accepts writes and reads back; one level more is an error
  const auto chain = [](int depth) {
    Node root;
    Node* at = &root;
    for (int i = 0; i < depth; ++i) {
      at->kids->emplace_back();
      at = &at->kids->back();
      at->v = i + 1;
    }
    return root;
  };
  {
    const Node ok = chain(nm::max_tagged_depth);
    auto w = enc(ok);
    auto r = nm::protobuf<Node>()(in_of(w));
    CHECK(r && same(ok, r->value));
    std::vector<std::byte> out;
    auto e = nm::protobuf_encode(chain(nm::max_tagged_depth + 1), out);
    CHECK(!e);
    if (!e) CHECK(e.error().message == "Node" && std::string_view(e.error().what).find("depth") != std::string_view::npos);
    CHECK(!nm::protobuf_size(chain(nm::max_tagged_depth + 1)));
  }
  // a sink that fails part-way: an error naming the place
  arena a;
  std::mt19937_64 rng(7);
  All x = gen<All>(rng, a, 0);
  x.leaf->s = std::string_view("a string long enough to be its own write .............................."
                               "......................................................................."
                               ".......................................................................");
  const auto w = enc(x);
  for (std::size_t budget = 0; budget < w.size(); budget += 3) {
    failing_sink fs{budget};
    auto e = nm::protobuf_encode(x, fs);
    CHECK(!e);
    if (!e) CHECK(e.error().message == "All" || e.error().message == "Leaf");
  }
}

// ------------------------------------------------------------------ Lance
static void test_lance_manifest() {
  // A manifest as nanolance writes it, read back field by field.
  const std::string_view meta_key = "k";
  const std::byte meta_val[] = {std::byte{1}, std::byte{2}};
  lance::Field f;
  f.type = lance::FieldType::LEAF;
  f.name = std::string_view("id");
  f.id = 0;
  f.parent_id = -1;
  f.logical_type = std::string_view("int64");
  f.nullable = true;
  f.encoding = lance::FieldEncoding::PLAIN;
  f.metadata->push_back({});
  f.metadata->back().key = meta_key;
  f.metadata->back().value = nm::bytes(meta_val);
  lance::DataFile df;
  df.path = std::string_view("abc.lance");
  df.fields.v = {0};
  df.column_indices.v = {0};
  df.file_major_version = 2;
  df.file_minor_version = 2;
  df.file_size_bytes = 1234;
  lance::DataFragment frag;
  frag.id = 0;
  frag.files->push_back(df);
  frag.physical_rows = 10;
  lance::Manifest m;
  m.fields->push_back(f);
  m.fragments->push_back(frag);
  m.version = 1;
  m.max_fragment_id = 0u;
  m.data_format = lance::DataStorageFormat{};
  m.data_format->value().file_format = std::string_view("lance");
  m.data_format->value().version = std::string_view("2.2");

  const auto w = enc(m);
  auto r = nm::protobuf<lance::Manifest>()(in_of(w));
  CHECK(r && same(m, r->value));
  if (r) {
    const auto& rf = r->value.fields->at(0);
    CHECK(*rf.parent_id == -1 && *rf.name == "id" && rf.metadata->size() == 1);
    CHECK(r->value.max_fragment_id->has_value() && **r->value.max_fragment_id == 0);  // optional: present
    CHECK(!r->value.fragments->at(0).deletion_file->has_value());
  }
}

int main() {
  test_golden();
  test_reader_rules();
  test_hostile();
  test_encode_errors();
  test_lance_manifest();

  roundtrip_property<All>("All", 3000, 1);
  roundtrip_property<Node>("Node", 1000, 2);
  roundtrip_property<lance::Manifest>("lance::Manifest", 1000, 3);
  roundtrip_property<lance::FileDescriptor>("lance::FileDescriptor", 500, 4);
  roundtrip_property<lance::ColumnMetadata>("lance::ColumnMetadata", 1000, 5);
  roundtrip_property<lance::Metadata>("lance::Metadata", 500, 6);

  if (failures) {
    std::printf("%d failure(s)\n", failures);
    return 1;
  }
  std::printf("protobuf: all tests passed\n");
  return 0;
}
