// Tests for nanom/tagged_encode.hpp: writing tagged messages (Thrift compact).
//
// Property tests over the whole Parquet model (nanom/formats/parquet_thrift.hpp). Random values of
// every message are GENERATED BY REFLECTION (any optional field present or not, random strings,
// lists built with list<E>::of), then:
//   * decode(encode(x)) == x, field by field;
//   * encode(decode(encode(x))) is byte-identical (decoded lists / structs are written verbatim);
//   * thrift_compact_size(x) == the bytes written;
//   * every too-small span_sink fails cleanly and is never written past (exact-size buffers: ASan);
// plus the encoder's error reporting (unset lazy<M>, oversized lengths, failing sinks).
#include <nanom/formats/parquet_thrift.hpp>
#include <nanom/tagged_encode.hpp>

#include "tagged_gen.hpp"

#include <cstdio>
#include <deque>
#include <memory>
#include <random>
#include <string>
#include <vector>

namespace nm = nanom;
namespace pq = nanom_formats::parquet;
using nanom_test::arena;
using nanom_test::gen;
using nanom_test::same;

static int failures = 0;
#define CHECK(cond)                                                        \
  do {                                                                     \
    if (!(cond)) {                                                         \
      std::printf("FAIL %s:%d: %s\n", __FILE__, __LINE__, #cond);          \
      ++failures;                                                          \
    }                                                                      \
  } while (0)

// ------------------------------------------------------------------ properties
template <class M>
void roundtrip_property(const char* name, int rounds, std::uint64_t seed) {
  std::mt19937_64 rng(seed);
  int bad = 0;
  for (int t = 0; t < rounds; ++t) {
    arena a;
    const M x = gen<M>(rng, a, 0);

    std::vector<std::byte> wire;
    auto n = nm::thrift_compact_encode(x, wire);
    if (!n || *n != wire.size()) { ++bad; continue; }
    auto size = nm::thrift_compact_size(x);
    if (!size || *size != wire.size()) { ++bad; continue; }

    auto back = nm::thrift_compact<M>()(nm::from(std::span<const std::byte>(wire)));
    if (!back || !back->rest.empty() || !same(x, back->value)) { ++bad; continue; }

    std::vector<std::byte> again;  // decoded lists are written verbatim: identical bytes
    if (!nm::thrift_compact_encode(back->value, again) || again != wire) { ++bad; continue; }

    // fixed buffers: exact size succeeds with identical bytes; every smaller one fails cleanly
    {
      std::vector<std::byte> exact(wire.size());
      nm::span_sink s{exact};
      if (!nm::thrift_compact_encode(x, s) || exact != wire) { ++bad; continue; }
    }
    const std::size_t step = wire.size() > 64 ? wire.size() / 16 : 1;
    for (std::size_t cap = 0; cap < wire.size(); cap += step) {
      std::vector<std::byte> small(cap);  // exact capacity: ASan catches any write past it
      nm::span_sink s{small};
      if (nm::thrift_compact_encode(x, s) || s.used > cap) { ++bad; break; }
    }
  }
  if (bad) std::printf("%s: %d of %d rounds failed\n", name, bad, rounds);
  CHECK(bad == 0);
}

// ------------------------------------------------------------------ errors
struct Inner {
  nm::field<1, std::int32_t> v;
};
struct Outer {
  nm::field<1, std::int32_t>       a;
  nm::field<2, nm::lazy<Inner>>    inner;
  nm::field<3, std::optional<nm::lazy<Inner>>> maybe;
};
NANOM_DESCRIBE(Inner, v);
NANOM_DESCRIBE(Outer, a, inner, maybe);

/// A sink that accepts `budget` bytes, then fails (a disk filling up, a closed socket).
struct failing_sink {
  std::size_t budget;
  bool put(const std::byte*, std::size_t n) {
    if (n > budget) return false;
    budget -= n;
    return true;
  }
};

static void test_errors() {
  // a required lazy<M> that was never set: an error naming where, not an empty struct
  Outer o;
  o.a = 7;
  std::vector<std::byte> out;
  auto r = nm::thrift_compact_encode(o, out);
  CHECK(!r);
  if (!r) CHECK(r.error().message == "Outer" && r.error().field == "inner");

  // set with lazy<M>::of: encodes, decodes, and decode() of the source returns the message
  Inner in;
  in.v = -5;
  o.inner = nm::lazy<Inner>::of(in);
  CHECK(o.inner->decode() && *o.inner->decode()->v == -5);
  out.clear();
  CHECK(nm::thrift_compact_encode(o, out));
  auto back = nm::thrift_compact<Outer>()(nm::from(std::span<const std::byte>(out)));
  CHECK(back && *back->value.a == 7 && !back->value.maybe->has_value());
  if (back) {
    auto d = back->value.inner->decode();
    CHECK(d && *d->v == -5);
    std::vector<std::byte> again;  // the decoded lazy is written back verbatim
    CHECK(nm::thrift_compact_encode(back->value, again) && again == out);
  }

  // a sink that fails part-way: an error, and the total never counts refused bytes
  for (std::size_t budget = 0; budget < out.size(); ++budget) {
    failing_sink fs{budget};
    CHECK(!nm::thrift_compact_encode(o, fs));
  }

  // lengths beyond the wire's i32 are refused before anything is written for them
  nm::counting_sink cs;
  nm::detail::tc::writer w(cs);
  CHECK(w.length(std::size_t(INT32_MAX)));
  CHECK(!w.err);
  CHECK(!w.length(std::size_t(INT32_MAX) + 1));
  CHECK(w.err != nullptr);
  nm::counting_sink cs2;
  nm::detail::tc::writer w2(cs2);
  w2.list_header(std::size_t(INT32_MAX) + 1, 5);
  CHECK(w2.err != nullptr);

  // a source list iterates, indexes and copies like a decoded one
  const std::int64_t vals[] = {1, -2, 3};
  const auto l = nm::list<std::int64_t>::of(vals);
  CHECK(l.size() == 3 && l.is_source() && *l.at(1) == -2 && !l.at(3));
  std::int64_t sum = 0;
  CHECK(l.for_each([&](std::int64_t v) { sum += v; }));
  CHECK(sum == 2 && l.to_vector()->size() == 3);
}

// ------------------------------------------------------------------ a real footer, written
static void test_footer_bytes() {
  // FileMetaData with one row group of one column, written and located like a real file
  const std::string_view path[] = {"id"};
  const pq::Encoding encs[] = {pq::Encoding::PLAIN, pq::Encoding::RLE};
  pq::ColumnMetaData cmd;
  cmd.type = pq::Type::INT64;
  cmd.encodings = nm::list<pq::Encoding>::of(encs);
  cmd.path_in_schema = nm::list<std::string_view>::of(path);
  cmd.codec = pq::CompressionCodec::ZSTD;
  cmd.num_values = 10;
  cmd.total_uncompressed_size = 100;
  cmd.total_compressed_size = 60;
  cmd.data_page_offset = 4;
  pq::ColumnChunk cc;
  cc.file_offset = 4;
  cc.meta_data = cmd;
  const pq::ColumnChunk ccs[] = {cc};
  pq::RowGroup rg;
  rg.columns = nm::list<pq::ColumnChunk>::of(ccs);
  rg.total_byte_size = 100;
  rg.num_rows = 10;
  const pq::RowGroup rgs[] = {rg};
  pq::SchemaElement root, col;
  root.name = std::string_view("schema");
  root.num_children = 1;
  col.type = pq::Type::INT64;
  col.repetition_type = pq::FieldRepetitionType::REQUIRED;
  col.name = std::string_view("id");
  const pq::SchemaElement schema[] = {root, col};
  pq::FileMetaData fmd;
  fmd.version = 1;
  fmd.schema = nm::list<pq::SchemaElement>::of(schema);
  fmd.num_rows = 10;
  fmd.row_groups = nm::list<pq::RowGroup>::of(rgs);
  fmd.created_by = std::string_view("nanom test");

  std::vector<std::byte> file = {std::byte('P'), std::byte('A'), std::byte('R'), std::byte('1')};
  const std::size_t at = file.size();
  auto n = nm::thrift_compact_encode(fmd, file);
  CHECK(n && *n == file.size() - at);
  const auto len = std::uint32_t(file.size() - at);
  for (int i = 0; i < 4; ++i) file.push_back(std::byte(len >> (8 * i)));
  for (char c : std::string_view("PAR1")) file.push_back(std::byte(c));
  auto md = pq::read_file_metadata(nm::from(std::span<const std::byte>(file)));
  CHECK(md && same(fmd, md->value));
  if (md) {
    auto g = md->value.row_groups->at(0);
    CHECK(g && g->columns->size() == 1);
  }
}

int main() {
  // every message of the Parquet model, including the page index and page headers
  roundtrip_property<pq::Statistics>("Statistics", 300, 1);
  roundtrip_property<pq::LogicalType>("LogicalType", 300, 2);
  roundtrip_property<pq::SchemaElement>("SchemaElement", 300, 3);
  roundtrip_property<pq::ColumnMetaData>("ColumnMetaData", 200, 4);
  roundtrip_property<pq::ColumnChunk>("ColumnChunk", 200, 5);
  roundtrip_property<pq::RowGroup>("RowGroup", 100, 6);
  roundtrip_property<pq::FileMetaData>("FileMetaData", 100, 7);
  roundtrip_property<pq::PageHeader>("PageHeader", 300, 8);
  roundtrip_property<pq::ColumnIndex>("ColumnIndex", 200, 9);
  roundtrip_property<pq::OffsetIndex>("OffsetIndex", 200, 10);
  test_errors();
  test_footer_bytes();
  if (failures) {
    std::printf("%d failure(s)\n", failures);
    return 1;
  }
  std::puts("tagged encode tests: all passed");
  return 0;
}
