#!/usr/bin/env python3
"""Generate `llms-full.txt` — the whole of nanom in a single fetch for an LLM.

The `llms.txt` standard (https://llmstxt.org) has two files: a curated index (`llms.txt`, committed by
hand) and an *expanded* companion (`llms-full.txt`) that inlines the actual content so one HTTP GET
gives a model the complete picture. This script builds the latter by concatenating the human prose
(README, DESIGN, the cheat sheet) with the **amalgamated single-file source** (`nanom-single.hpp`, from
tools/amalgamate.py) — architecture *and* full implementation, no directory crawl required.

It is a generated artifact (gitignored); CI / the Pages build regenerate it so it never drifts.

usage: python3 tools/gen_llms.py [--out llms-full.txt] [--single nanom-single.hpp]
       (if --single is missing it is produced on the fly via tools/amalgamate.py)
"""
import argparse
import pathlib
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
# (repo-relative path, human heading) pairs, in reading order.
PROSE = [
    ("README.md", "README"),
    ("DESIGN.md", "DESIGN"),
    ("docs/CHEATSHEET.md", "Cheat sheet (nom name -> nanom name)"),
    ("docs/BENCH_RUST_NOM.md", "Benchmark: nanom vs stable Rust nom (streaming pcapng)"),
]


def section(title: str, body: str) -> str:
    rule = "=" * 100
    return f"{rule}\n# {title}\n{rule}\n\n{body.rstrip()}\n\n"


def main(argv) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default="llms-full.txt")
    ap.add_argument("--single", default="nanom-single.hpp",
                    help="path to the amalgamated header; generated via amalgamate.py if absent")
    a = ap.parse_args(argv[1:])

    parts = [
        "nanom — full context for language models (generated by tools/gen_llms.py; do not edit).\n"
        "Source of truth: https://github.com/yoavbendor/nanom . License: Apache-2.0.\n"
        "This file inlines the prose docs and the entire amalgamated single-file header so one fetch\n"
        "gives you both the architecture and the complete implementation.\n\n",
    ]
    for rel, title in PROSE:
        p = ROOT / rel
        if p.exists():
            parts.append(section(title, p.read_text()))
        else:
            print(f"warning: {rel} missing, skipping", file=sys.stderr)

    single = pathlib.Path(a.single)
    if not single.is_absolute():
        single = ROOT / single
    if not single.exists():
        print(f"amalgamating {single.name} via tools/amalgamate.py ...", file=sys.stderr)
        subprocess.run([sys.executable, str(ROOT / "tools" / "amalgamate.py"), "--out", str(single)],
                       check=True)
    parts.append(section("Complete source — nanom-single.hpp (generated amalgamation)",
                         "```cpp\n" + single.read_text().rstrip() + "\n```"))

    out = pathlib.Path(a.out)
    text = "".join(parts)
    out.write_text(text)
    print(f"wrote {out}: {len(text):,} bytes, {text.count(chr(10)):,} lines", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
