var annotated_dup =
[
    [ "nanom", "namespacenanom.html", [
      [ "codec", "namespacenanom_1_1codec.html", [
        [ "fsst", "namespacenanom_1_1codec_1_1fsst.html", [
          [ "enc_detail", "namespacenanom_1_1codec_1_1fsst_1_1enc__detail.html", [
            [ "symbol", "structnanom_1_1codec_1_1fsst_1_1enc__detail_1_1symbol.html", "structnanom_1_1codec_1_1fsst_1_1enc__detail_1_1symbol" ]
          ] ],
          [ "encoder", "structnanom_1_1codec_1_1fsst_1_1encoder.html", "structnanom_1_1codec_1_1fsst_1_1encoder" ],
          [ "symbol_table", "structnanom_1_1codec_1_1fsst_1_1symbol__table.html", "structnanom_1_1codec_1_1fsst_1_1symbol__table" ]
        ] ],
        [ "codec_error", "structnanom_1_1codec_1_1codec__error.html", "structnanom_1_1codec_1_1codec__error" ]
      ] ],
      [ "columnar", "namespacenanom_1_1columnar.html", [
        [ "enc_detail", "namespacenanom_1_1columnar_1_1enc__detail.html", [
          [ "probe_slots", "structnanom_1_1columnar_1_1enc__detail_1_1probe__slots.html", "structnanom_1_1columnar_1_1enc__detail_1_1probe__slots" ]
        ] ],
        [ "binary_stats", "structnanom_1_1columnar_1_1binary__stats.html", "structnanom_1_1columnar_1_1binary__stats" ],
        [ "dremel_node", "structnanom_1_1columnar_1_1dremel__node.html", "structnanom_1_1columnar_1_1dremel__node" ],
        [ "fixed_dictionary", "classnanom_1_1columnar_1_1fixed__dictionary.html", "classnanom_1_1columnar_1_1fixed__dictionary" ],
        [ "kernel_status", "structnanom_1_1columnar_1_1kernel__status.html", "structnanom_1_1columnar_1_1kernel__status" ],
        [ "rle_bp_decoder", "classnanom_1_1columnar_1_1rle__bp__decoder.html", "classnanom_1_1columnar_1_1rle__bp__decoder" ],
        [ "slot_counts", "structnanom_1_1columnar_1_1slot__counts.html", "structnanom_1_1columnar_1_1slot__counts" ],
        [ "string_dictionary", "classnanom_1_1columnar_1_1string__dictionary.html", "classnanom_1_1columnar_1_1string__dictionary" ],
        [ "value_stats", "structnanom_1_1columnar_1_1value__stats.html", "structnanom_1_1columnar_1_1value__stats" ]
      ] ],
      [ "bdone", "structnanom_1_1bdone.html", "structnanom_1_1bdone" ],
      [ "bit_input", "structnanom_1_1bit__input.html", "structnanom_1_1bit__input" ],
      [ "bulk_table", "classnanom_1_1bulk__table.html", "classnanom_1_1bulk__table" ],
      [ "calc_t", "structnanom_1_1calc__t.html", "structnanom_1_1calc__t" ],
      [ "checksum_t", "structnanom_1_1checksum__t.html", "structnanom_1_1checksum__t" ],
      [ "computed", "structnanom_1_1computed.html", "structnanom_1_1computed" ],
      [ "counting_sink", "structnanom_1_1counting__sink.html", "structnanom_1_1counting__sink" ],
      [ "describe", "structnanom_1_1describe.html", null ],
      [ "done", "structnanom_1_1done.html", "structnanom_1_1done" ],
      [ "emit_ctx", "structnanom_1_1emit__ctx.html", "structnanom_1_1emit__ctx" ],
      [ "empty_struct", "structnanom_1_1empty__struct.html", "structnanom_1_1empty__struct" ],
      [ "encode_error", "structnanom_1_1encode__error.html", "structnanom_1_1encode__error" ],
      [ "endian_scalar", "structnanom_1_1endian__scalar.html", "structnanom_1_1endian__scalar" ],
      [ "error", "structnanom_1_1error.html", "structnanom_1_1error" ],
      [ "expected", "classnanom_1_1expected.html", "classnanom_1_1expected" ],
      [ "field", "structnanom_1_1field.html", "structnanom_1_1field" ],
      [ "fixed_string", "structnanom_1_1fixed__string.html", "structnanom_1_1fixed__string" ],
      [ "ibits", "structnanom_1_1ibits.html", "structnanom_1_1ibits" ],
      [ "input", "structnanom_1_1input.html", "structnanom_1_1input" ],
      [ "lazy", "classnanom_1_1lazy.html", "classnanom_1_1lazy" ],
      [ "le_array", "classnanom_1_1le__array.html", "classnanom_1_1le__array" ],
      [ "list", "classnanom_1_1list.html", "classnanom_1_1list" ],
      [ "par_exec", "structnanom_1_1par__exec.html", "structnanom_1_1par__exec" ],
      [ "pb_box", "classnanom_1_1pb__box.html", "classnanom_1_1pb__box" ],
      [ "pb_fixed", "structnanom_1_1pb__fixed.html", "structnanom_1_1pb__fixed" ],
      [ "pb_lazy", "classnanom_1_1pb__lazy.html", "classnanom_1_1pb__lazy" ],
      [ "pb_sint", "structnanom_1_1pb__sint.html", "structnanom_1_1pb__sint" ],
      [ "pkt_ref", "structnanom_1_1pkt__ref.html", "structnanom_1_1pkt__ref" ],
      [ "schema_field", "structnanom_1_1schema__field.html", "structnanom_1_1schema__field" ],
      [ "schema_node", "structnanom_1_1schema__node.html", "structnanom_1_1schema__node" ],
      [ "seg_done", "structnanom_1_1seg__done.html", "structnanom_1_1seg__done" ],
      [ "seg_input", "structnanom_1_1seg__input.html", "structnanom_1_1seg__input" ],
      [ "seg_subrange", "classnanom_1_1seg__subrange.html", "classnanom_1_1seg__subrange" ],
      [ "seg_window", "classnanom_1_1seg__window.html", "classnanom_1_1seg__window" ],
      [ "segments", "classnanom_1_1segments.html", "classnanom_1_1segments" ],
      [ "seq_exec", "structnanom_1_1seq__exec.html", "structnanom_1_1seq__exec" ],
      [ "single_segment", "classnanom_1_1single__segment.html", "classnanom_1_1single__segment" ],
      [ "soa", "classnanom_1_1soa.html", "classnanom_1_1soa" ],
      [ "span_sink", "structnanom_1_1span__sink.html", "structnanom_1_1span__sink" ],
      [ "ubits", "structnanom_1_1ubits.html", "structnanom_1_1ubits" ],
      [ "unexpected", "classnanom_1_1unexpected.html", "classnanom_1_1unexpected" ],
      [ "unit", "structnanom_1_1unit.html", null ],
      [ "unknown_fields", "structnanom_1_1unknown__fields.html", "structnanom_1_1unknown__fields" ],
      [ "vector_sink", "structnanom_1_1vector__sink.html", "structnanom_1_1vector__sink" ],
      [ "view", "structnanom_1_1view.html", "structnanom_1_1view" ]
    ] ],
    [ "nanom_formats", "namespacenanom__formats.html", [
      [ "lance", "namespacenanom__formats_1_1lance.html", [
        [ "Any", "structnanom__formats_1_1lance_1_1Any.html", "structnanom__formats_1_1lance_1_1Any" ],
        [ "ArrayEncoding", "structnanom__formats_1_1lance_1_1ArrayEncoding.html", "structnanom__formats_1_1lance_1_1ArrayEncoding" ],
        [ "Binary", "structnanom__formats_1_1lance_1_1Binary.html", "structnanom__formats_1_1lance_1_1Binary" ],
        [ "Bitpacked20", "structnanom__formats_1_1lance_1_1Bitpacked20.html", "structnanom__formats_1_1lance_1_1Bitpacked20" ],
        [ "BitpackedForNonNeg", "structnanom__formats_1_1lance_1_1BitpackedForNonNeg.html", "structnanom__formats_1_1lance_1_1BitpackedForNonNeg" ],
        [ "Buffer", "structnanom__formats_1_1lance_1_1Buffer.html", "structnanom__formats_1_1lance_1_1Buffer" ],
        [ "BufferCompression", "structnanom__formats_1_1lance_1_1BufferCompression.html", "structnanom__formats_1_1lance_1_1BufferCompression" ],
        [ "ByteStreamSplit", "structnanom__formats_1_1lance_1_1ByteStreamSplit.html", "structnanom__formats_1_1lance_1_1ByteStreamSplit" ],
        [ "ColumnEncoding20", "structnanom__formats_1_1lance_1_1ColumnEncoding20.html", "structnanom__formats_1_1lance_1_1ColumnEncoding20" ],
        [ "ColumnMetadata", "structnanom__formats_1_1lance_1_1ColumnMetadata.html", "structnanom__formats_1_1lance_1_1ColumnMetadata" ],
        [ "Compression", "structnanom__formats_1_1lance_1_1Compression.html", "structnanom__formats_1_1lance_1_1Compression" ],
        [ "CompressiveEncoding", "structnanom__formats_1_1lance_1_1CompressiveEncoding.html", "structnanom__formats_1_1lance_1_1CompressiveEncoding" ],
        [ "Constant20", "structnanom__formats_1_1lance_1_1Constant20.html", "structnanom__formats_1_1lance_1_1Constant20" ],
        [ "ConstantLayout", "structnanom__formats_1_1lance_1_1ConstantLayout.html", "structnanom__formats_1_1lance_1_1ConstantLayout" ],
        [ "DataFile", "structnanom__formats_1_1lance_1_1DataFile.html", "structnanom__formats_1_1lance_1_1DataFile" ],
        [ "DataFragment", "structnanom__formats_1_1lance_1_1DataFragment.html", "structnanom__formats_1_1lance_1_1DataFragment" ],
        [ "DataStorageFormat", "structnanom__formats_1_1lance_1_1DataStorageFormat.html", "structnanom__formats_1_1lance_1_1DataStorageFormat" ],
        [ "DeletionFile", "structnanom__formats_1_1lance_1_1DeletionFile.html", "structnanom__formats_1_1lance_1_1DeletionFile" ],
        [ "Dictionary20", "structnanom__formats_1_1lance_1_1Dictionary20.html", "structnanom__formats_1_1lance_1_1Dictionary20" ],
        [ "DirectEncoding", "structnanom__formats_1_1lance_1_1DirectEncoding.html", "structnanom__formats_1_1lance_1_1DirectEncoding" ],
        [ "Encoding", "structnanom__formats_1_1lance_1_1Encoding.html", "structnanom__formats_1_1lance_1_1Encoding" ],
        [ "EncodingAny", "structnanom__formats_1_1lance_1_1EncodingAny.html", "structnanom__formats_1_1lance_1_1EncodingAny" ],
        [ "Field", "structnanom__formats_1_1lance_1_1Field.html", "structnanom__formats_1_1lance_1_1Field" ],
        [ "FileDescriptor", "structnanom__formats_1_1lance_1_1FileDescriptor.html", "structnanom__formats_1_1lance_1_1FileDescriptor" ],
        [ "FixedSizeBinary", "structnanom__formats_1_1lance_1_1FixedSizeBinary.html", "structnanom__formats_1_1lance_1_1FixedSizeBinary" ],
        [ "FixedSizeList20", "structnanom__formats_1_1lance_1_1FixedSizeList20.html", "structnanom__formats_1_1lance_1_1FixedSizeList20" ],
        [ "FixedSizeList21", "structnanom__formats_1_1lance_1_1FixedSizeList21.html", "structnanom__formats_1_1lance_1_1FixedSizeList21" ],
        [ "Flat", "structnanom__formats_1_1lance_1_1Flat.html", "structnanom__formats_1_1lance_1_1Flat" ],
        [ "Flat20", "structnanom__formats_1_1lance_1_1Flat20.html", "structnanom__formats_1_1lance_1_1Flat20" ],
        [ "Fsst", "structnanom__formats_1_1lance_1_1Fsst.html", "structnanom__formats_1_1lance_1_1Fsst" ],
        [ "Fsst20", "structnanom__formats_1_1lance_1_1Fsst20.html", "structnanom__formats_1_1lance_1_1Fsst20" ],
        [ "FullZipLayout", "structnanom__formats_1_1lance_1_1FullZipLayout.html", "structnanom__formats_1_1lance_1_1FullZipLayout" ],
        [ "General", "structnanom__formats_1_1lance_1_1General.html", "structnanom__formats_1_1lance_1_1General" ],
        [ "IndexFile", "structnanom__formats_1_1lance_1_1IndexFile.html", "structnanom__formats_1_1lance_1_1IndexFile" ],
        [ "IndexMetadata", "structnanom__formats_1_1lance_1_1IndexMetadata.html", "structnanom__formats_1_1lance_1_1IndexMetadata" ],
        [ "IndexSection", "structnanom__formats_1_1lance_1_1IndexSection.html", "structnanom__formats_1_1lance_1_1IndexSection" ],
        [ "InlineBitpacking", "structnanom__formats_1_1lance_1_1InlineBitpacking.html", "structnanom__formats_1_1lance_1_1InlineBitpacking" ],
        [ "List20", "structnanom__formats_1_1lance_1_1List20.html", "structnanom__formats_1_1lance_1_1List20" ],
        [ "Manifest", "structnanom__formats_1_1lance_1_1Manifest.html", "structnanom__formats_1_1lance_1_1Manifest" ],
        [ "Metadata", "structnanom__formats_1_1lance_1_1Metadata.html", "structnanom__formats_1_1lance_1_1Metadata" ],
        [ "MetadataEntry", "structnanom__formats_1_1lance_1_1MetadataEntry.html", "structnanom__formats_1_1lance_1_1MetadataEntry" ],
        [ "MiniBlockLayout", "structnanom__formats_1_1lance_1_1MiniBlockLayout.html", "structnanom__formats_1_1lance_1_1MiniBlockLayout" ],
        [ "NoNull", "structnanom__formats_1_1lance_1_1NoNull.html", "structnanom__formats_1_1lance_1_1NoNull" ],
        [ "Nullable", "structnanom__formats_1_1lance_1_1Nullable.html", "structnanom__formats_1_1lance_1_1Nullable" ],
        [ "OutOfLineBitpacking", "structnanom__formats_1_1lance_1_1OutOfLineBitpacking.html", "structnanom__formats_1_1lance_1_1OutOfLineBitpacking" ],
        [ "PackedStruct", "structnanom__formats_1_1lance_1_1PackedStruct.html", "structnanom__formats_1_1lance_1_1PackedStruct" ],
        [ "Page", "structnanom__formats_1_1lance_1_1Page.html", "structnanom__formats_1_1lance_1_1Page" ],
        [ "PageLayout", "structnanom__formats_1_1lance_1_1PageLayout.html", "structnanom__formats_1_1lance_1_1PageLayout" ],
        [ "Rle", "structnanom__formats_1_1lance_1_1Rle.html", "structnanom__formats_1_1lance_1_1Rle" ],
        [ "Schema", "structnanom__formats_1_1lance_1_1Schema.html", "structnanom__formats_1_1lance_1_1Schema" ],
        [ "SomeNull", "structnanom__formats_1_1lance_1_1SomeNull.html", "structnanom__formats_1_1lance_1_1SomeNull" ],
        [ "StringEntry", "structnanom__formats_1_1lance_1_1StringEntry.html", "structnanom__formats_1_1lance_1_1StringEntry" ],
        [ "Timestamp", "structnanom__formats_1_1lance_1_1Timestamp.html", "structnanom__formats_1_1lance_1_1Timestamp" ],
        [ "Uuid", "structnanom__formats_1_1lance_1_1Uuid.html", "structnanom__formats_1_1lance_1_1Uuid" ],
        [ "Variable", "structnanom__formats_1_1lance_1_1Variable.html", "structnanom__formats_1_1lance_1_1Variable" ],
        [ "WriterVersion", "structnanom__formats_1_1lance_1_1WriterVersion.html", "structnanom__formats_1_1lance_1_1WriterVersion" ]
      ] ],
      [ "parquet", "namespacenanom__formats_1_1parquet.html", [
        [ "ColumnChunk", "structnanom__formats_1_1parquet_1_1ColumnChunk.html", "structnanom__formats_1_1parquet_1_1ColumnChunk" ],
        [ "ColumnIndex", "structnanom__formats_1_1parquet_1_1ColumnIndex.html", "structnanom__formats_1_1parquet_1_1ColumnIndex" ],
        [ "ColumnMetaData", "structnanom__formats_1_1parquet_1_1ColumnMetaData.html", "structnanom__formats_1_1parquet_1_1ColumnMetaData" ],
        [ "ColumnOrder", "structnanom__formats_1_1parquet_1_1ColumnOrder.html", "structnanom__formats_1_1parquet_1_1ColumnOrder" ],
        [ "DataPageHeader", "structnanom__formats_1_1parquet_1_1DataPageHeader.html", "structnanom__formats_1_1parquet_1_1DataPageHeader" ],
        [ "DataPageHeaderV2", "structnanom__formats_1_1parquet_1_1DataPageHeaderV2.html", "structnanom__formats_1_1parquet_1_1DataPageHeaderV2" ],
        [ "DecimalType", "structnanom__formats_1_1parquet_1_1DecimalType.html", "structnanom__formats_1_1parquet_1_1DecimalType" ],
        [ "DictionaryPageHeader", "structnanom__formats_1_1parquet_1_1DictionaryPageHeader.html", "structnanom__formats_1_1parquet_1_1DictionaryPageHeader" ],
        [ "FileMetaData", "structnanom__formats_1_1parquet_1_1FileMetaData.html", "structnanom__formats_1_1parquet_1_1FileMetaData" ],
        [ "footer_location", "structnanom__formats_1_1parquet_1_1footer__location.html", "structnanom__formats_1_1parquet_1_1footer__location" ],
        [ "IntType", "structnanom__formats_1_1parquet_1_1IntType.html", "structnanom__formats_1_1parquet_1_1IntType" ],
        [ "KeyValue", "structnanom__formats_1_1parquet_1_1KeyValue.html", "structnanom__formats_1_1parquet_1_1KeyValue" ],
        [ "LogicalType", "structnanom__formats_1_1parquet_1_1LogicalType.html", "structnanom__formats_1_1parquet_1_1LogicalType" ],
        [ "OffsetIndex", "structnanom__formats_1_1parquet_1_1OffsetIndex.html", "structnanom__formats_1_1parquet_1_1OffsetIndex" ],
        [ "PageEncodingStats", "structnanom__formats_1_1parquet_1_1PageEncodingStats.html", "structnanom__formats_1_1parquet_1_1PageEncodingStats" ],
        [ "PageHeader", "structnanom__formats_1_1parquet_1_1PageHeader.html", "structnanom__formats_1_1parquet_1_1PageHeader" ],
        [ "PageLocation", "structnanom__formats_1_1parquet_1_1PageLocation.html", "structnanom__formats_1_1parquet_1_1PageLocation" ],
        [ "RowGroup", "structnanom__formats_1_1parquet_1_1RowGroup.html", "structnanom__formats_1_1parquet_1_1RowGroup" ],
        [ "SchemaElement", "structnanom__formats_1_1parquet_1_1SchemaElement.html", "structnanom__formats_1_1parquet_1_1SchemaElement" ],
        [ "SortingColumn", "structnanom__formats_1_1parquet_1_1SortingColumn.html", "structnanom__formats_1_1parquet_1_1SortingColumn" ],
        [ "Statistics", "structnanom__formats_1_1parquet_1_1Statistics.html", "structnanom__formats_1_1parquet_1_1Statistics" ],
        [ "TimestampType", "structnanom__formats_1_1parquet_1_1TimestampType.html", "structnanom__formats_1_1parquet_1_1TimestampType" ],
        [ "TimeType", "structnanom__formats_1_1parquet_1_1TimeType.html", "structnanom__formats_1_1parquet_1_1TimeType" ],
        [ "TimeUnit", "structnanom__formats_1_1parquet_1_1TimeUnit.html", "structnanom__formats_1_1parquet_1_1TimeUnit" ]
      ] ]
    ] ]
];